apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gedwiz7ul-nodejs 
  janus-idp.io/tekton: gedwiz7ul-nodejs
  backstage.io/kubernetes-id: gedwiz7ul-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gedwiz7ul-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  