apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gedwiz7ul-nodejs
  janus-idp.io/tekton: gedwiz7ul-nodejs
  backstage.io/kubernetes-id: gedwiz7ul-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gedwiz7ul-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
