apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gedwiz7ul-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8833e0520c9510a08a0f10016bece8d028d6cd6f@sha256:f4e316fe0ec22e9a8eed6b1661f23025b636dd106623bdcf4ce4806780743a96
          name: container-image
